 version: '3.3'

 services:

  prometheus:
     image: prom/prometheus:latest
     user: "root"
     container_name: prometheus
     restart: unless-stopped
     volumes:
       -  /prometheus.yml:/etc/prometheus/
       - ./prometheus:/prometheus
     command:
       - '--config.file=/etc/prometheus/prometheus.yml'
       - '--storage.tsdb.path=/prometheus'
         # - '--storage.tsdb.retention=200h'  
         # - '--alertmanager.url=http://alertmanager:9093'
     expose:
       - 9090
     ports:
       - 9090:9090
     links:
       - cadvisor:cadvisor
       - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 9100:9100      

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
  
  grafana:
    image: grafana/grafana:latest
    user: "472"
    container_name: grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    expose:
      - 3000      
    ports: 
      - 3000:3000    
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}  
      - GF_USERS_ALLOW_SIGN_UP=false
 volumes:
     prometheus: {}
     grafana: {}
